name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'features/*'

jobs:
  docker:
    name: Containerization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
