name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'features/*'

jobs:
  docker:
    name: Containerization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github-repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}          

      - name: Docker Build for Testing
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/github-action-nginx:latest

      - name: Docker Image for Testing
        run: |
          docker images
          # Add additional commands here if needed to test the built image, like running it:
          # docker run -d -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/github-action-nginx:latest

      - name: Container registry push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/github-action-nginx:latest
            ghcr.io${{ github-repository_owner }}/github-action-nginx:latest