name: Solar System Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'features/*'

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v4

      - name: Setup Node.js Version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        run: npm test
        
